
image:
  repository: atmoz/sftp
  tag: latest
  pullPolicy: IfNotPresent
  args: "foo:foo:1000"

service:
  type: NodePort
  port: 22

volumes:
  - name: myvolume
    persistentVolumeClaim:
      claimName: myvolume

volumeMounts:
  - name: myvolume
    mountPath: "/home/foo"

resources:
  requests:
    memory: 256Mi
    cpu: 0.5
  limits:
    memory: 512Mi
    cpu: 1

nodeSelector: {}

tolerations: []

affinity: {}
