
replicaCount: 1

image:
  repository: hacdias/filebrowser
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - filebrowser.bananaspliff.org
  tls:
   - secretName: filebrowser-bananaspliff-org
     hosts:
       - filebrowser.bananaspliff.org

volumes:
  - name: myvolume
    persistentVolumeClaim:
      claimName: myvolume

volumeMounts:
  - name: myvolume
    mountPath: "/etc/config.json"
    subPath: "configs/filebrowser/config.json"
  - name: myvolume
    mountPath: "/etc/database.db"
    subPath: "configs/filebrowser/database.db"
  - name: myvolume
    mountPath: "/srv"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
