apiVersion: v1
kind: Service
metadata:
  name: {{ template "sftp.fullname" . }}
  labels:
    app: {{ template "sftp.name" . }}
    chart: {{ template "sftp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 22
      protocol: TCP
      name: ssh
  selector:
    app: {{ template "sftp.name" . }}
    release: {{ .Release.Name }}
