
replicaCount: 1

image:
  repository: emby/embyserver
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: UID
    value: "1000"
  - name: GID
    value: "1000"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  hosts:
  - name: emby.local
    tls: false
    tlsSecret: emby.local-tls
    annotations:
    #  kubernetes.io/ingress.class: nginx
    #  kubernetes.io/tls-acme: true

  secrets:

volumes:
  - name: myvolume
    persistentVolumeClaim:
      claimName: myvolume

volumeMounts:
  - name: myvolume
    mountPath: "/config"
    subPath: "configs/emby"
  - name: myvolume
    mountPath: "/medias"
    subPath: "medias"

resources:
  requests:
    memory: 2048Mi
    cpu: 1
  limits:
    memory: 4096Mi
    cpu: 5

nodeSelector: {}

tolerations: []

affinity: {}
