version: '2'
services:
  flood:
    image: romancin/rutorrent-flood:latest
    container_name: rutorrent-flood
    ports:
      - ${PORT1}:443
      - ${PORT2}:3000
      - ${PORT3}:51415-51415
    environment:
      - PGID=0
      - PUID=0
      - TZ=${TIMEZONE}
    volumes:
      - /data/config:/config
      - /data/downloads:/downloads
