version: '2'
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=root
      - PGID=root
#    volumes:
#      - ./volumes/xo-server:/storage

#  redis:
#    container_name: xoa-redis
#    image: redis:alpine
#    command: redis-server --appendonly yes
#    volumes:
#      - ./volumes/redis:/data
