version: '2'
services:
  orchestra:
    image: ezka77/xen-orchestra-ce
    container_name: xoa
    ports:
      - "8000:80"
    depends_on:
      - redis
    environment:
      - DEBUG=xo:main
      - NODE_ENV=production
      - XOA_PLAN=5
    volumes:
      - ./volumes/xo-server:/storage
  redis:
    container_name: xoa-redis
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - ./volumes/redis:/data
